language: node_js
node_js:
- 16
before_deploy:
- npm run build
deploy:
  provider: npm
  email: madison.barry@hey.com
  api_key:
    secure: G24b/HmEGCLQ4RZqCBR3iFgKazRZN0Eb6n7TIbAzPsskwcbaGzysWVkpoN3DwnWINwYSyn90qQrRzrcVl6gORkPIUIE2WgbRGEhiIWHyUkPLK5w0gDrQrBb8H4SAVjm/lPSizXvOeEk7QmJQkRXCnbjjCsMkj4ZUcqqZNQECgEKCxB3Q2DmsPmV/FJUZaNI3H9BcgdeyjEC6iuEZfIsf1qO6OSSDS97TloRd8+8i8kU0S2ucpg1YeIFarixf17yCKHYeMb+vf06hCuFBBxz52hmCjz3i2SDkzNgeGDFVYCTl5/hVOuQkk5ryKA33Jd8w40t2e+ZQYwvjV5w0F1drMPb3piGXJaZCpb/PTsdoO98loxdIP9sgCxQAKmjLQvKjfc+IgWKtclu6Mc+lh02ny7P3mS0flYSjjFFAi/qmoPWHUaXqK2pZk9+dTxnHt1anXNbDCoDCnEslLW9jjm/9UGs42yHkoGOjYSaliXd+8ZZTQVOgd651/UfwjMeU/4K6cEXd6wlwIzSggpE33CH8gWnxnFnfWYhwcA81l24AtV+xWCgQU10JcLx5bIvO0FzmFX0Eyj25Jd0kIGOqe4Uv61kbQKbU4EacFBeR5sDoJ8S/plgm0EnvGPs0iT/5uBZV2ksCoKy8U9lCQ3KA/E26Gya/eU2WvbIeSov7k1HdF5Y=
  on:
    tags: true
    repo: TBPixel/functional-finite-state-machine
